### ISSUE TITLE
setting servicecall to a Cancel status always generates an error

### ISSUE THREAD

**Issue by optmsp** [Anteris-Dev/autotask-client#60]
So this can be reproduced. I'm hoping I'm doing something wrong.

Create a service call status of type Cancelled in Autotask. Let's called in "Declined".

```
        $rmtServiceCall = $autotaskClient->serviceCalls()->findById($psaID);
        $rmtServiceCall->status = (Declined-status-ID)
        $autotaskClient->serviceCalls()->update($rmtServiceCall);
```

Every time, this will generate an error from the Autotask API:

```
Exception 'GuzzleHttp\Exception\ServerException' with message 'Server error: `PUT https://webservices2.autotask.net/ATServicesRest/v1.0/ServiceCalls` resulted in a `500 Internal Server Error` response:
{"errors":["The startDateTime, endDateTime and isComplete cannot be edited if status is of type \"Canceled\".","Error up (truncated...)
'

in /home/forge/giantrocketship.net/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113

Stack trace:
#0 /home/forge/project/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create()
#1 /home/forge/project/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#2 /home/forge/project/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler()
#3 /home/forge/project/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /home/forge/project/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run()
#5 /home/forge/project/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /home/forge/project/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /home/forge/project/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /home/forge/project/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /home/forge/project/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Promise\Promise->wait()
#10 /home/forge/project/vendor/guzzlehttp/guzzle/src/ClientTrait.php(78): GuzzleHttp\Client->request()
#11 /home/forge/project/vendor/anteris-dev/autotask-client/src/HttpClient.php(117): GuzzleHttp\Client->put()
```

**Comment by optmsp** [comment]
Okay, I think the issue here is that we are doing a PUT vs a PATCH update.. can't be sure but I suspect that's the case.

**Comment by aidan-casey** [comment]
@optmsp - I am thinking this is not an issue with the package. The error thrown is indicating that those fields cannot be modified when it is in that status?

**Comment by optmsp** [comment]
I have a query out to the API team at Autotask. I'm totally unclear why this error is happening.

I agree it's doubtful that it's your code. 99% sure it's a glitch in the API or a missing "something" that's not in their docs..

**Comment by optmsp** [comment]
Side note, I think I tried doing a patch vs a put and it still failed. It's been a few weeks, but I do remember trying that as well. (I just did a raw http call vs using your code.)

**Comment by optmsp** [comment]
So @aidan-casey now that we have the GET/PUT update in place, I have my guy checking on this as well. Will report back.
